package org.suree.domain;

public class TaiKyokuTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taikyoku_table.id
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taikyoku_table.username
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taikyoku_table.mode
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    private Integer mode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taikyoku_table.rank
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    private Byte rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taikyoku_table.logcode
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    private String logcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taikyoku_table.content
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taikyoku_table.id
     *
     * @return the value of taikyoku_table.id
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taikyoku_table.id
     *
     * @param id the value for taikyoku_table.id
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taikyoku_table.username
     *
     * @return the value of taikyoku_table.username
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taikyoku_table.username
     *
     * @param username the value for taikyoku_table.username
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taikyoku_table.mode
     *
     * @return the value of taikyoku_table.mode
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    public Integer getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taikyoku_table.mode
     *
     * @param mode the value for taikyoku_table.mode
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    public void setMode(Integer mode) {
        this.mode = mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taikyoku_table.rank
     *
     * @return the value of taikyoku_table.rank
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    public Byte getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taikyoku_table.rank
     *
     * @param rank the value for taikyoku_table.rank
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    public void setRank(Byte rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taikyoku_table.logcode
     *
     * @return the value of taikyoku_table.logcode
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    public String getLogcode() {
        return logcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taikyoku_table.logcode
     *
     * @param logcode the value for taikyoku_table.logcode
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    public void setLogcode(String logcode) {
        this.logcode = logcode == null ? null : logcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taikyoku_table.content
     *
     * @return the value of taikyoku_table.content
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taikyoku_table.content
     *
     * @param content the value for taikyoku_table.content
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}