package org.suree.mappers;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.suree.domain.TaiKyokuTable;
import org.suree.domain.TaiKyokuTableExample;

public interface TaiKyokuTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taikyoku_table
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    int countByExample(TaiKyokuTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taikyoku_table
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    int deleteByExample(TaiKyokuTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taikyoku_table
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taikyoku_table
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    int insert(TaiKyokuTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taikyoku_table
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    int insertSelective(TaiKyokuTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taikyoku_table
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    List<TaiKyokuTable> selectByExampleWithBLOBs(TaiKyokuTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taikyoku_table
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    List<TaiKyokuTable> selectByExample(TaiKyokuTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taikyoku_table
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    TaiKyokuTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taikyoku_table
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    int updateByExampleSelective(@Param("record") TaiKyokuTable record, @Param("example") TaiKyokuTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taikyoku_table
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") TaiKyokuTable record, @Param("example") TaiKyokuTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taikyoku_table
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    int updateByExample(@Param("record") TaiKyokuTable record, @Param("example") TaiKyokuTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taikyoku_table
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    int updateByPrimaryKeySelective(TaiKyokuTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taikyoku_table
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(TaiKyokuTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taikyoku_table
     *
     * @mbggenerated Sun Nov 13 21:40:26 CST 2016
     */
    int updateByPrimaryKey(TaiKyokuTable record);
}